config/routes.rb
Rails.application.routes.draw do
    resources :impression, only: :create
    resources :analytics, only: :index
end

app/models/impression.rb
class Impression < ActiveRecord::Base
  attr_accessor :app_name, :app_version, :device, :user_agent, :now_url
  before_create :analytics

  def analytics
    self.url = now_url
    self.browser = browser_check
    self.browser_version = browser_version_check
    self.platform = device
  end

  def self.day_select
    from = Time.now.at_beginning_of_day
    to = from.at_end_of_day
    where(created_at: from...to)
  end

  def self.week_select
    to = Time.now.at_beginning_of_day
    from = (to - 7.day).at_end_of_day
    where(created_at: from...to)
  end

  def self.month_select
    from = Time.now.beginning_of_month
    to = Time.now.end_of_month
    where(created_at: from...to)
  end

  def self.url_count
    group(:url).count
  end

  def self.browser_count
    group(:browser).count
  end

  def self.browser_version_count
    group(:browser_version).count
  end

  def self.platform_count
    group(:platform).count
  end

  private

    # Browser種類を判定する
    def browser_check
      # 　IE判定
      if app_name.include? 'Internet Explorer'
        'Internet Explorer'
        # Opera判定
      elsif app_name.include? 'Opera'
        'Opera'
        # Safari Chrome判定
      elsif app_version.include? 'Safari'
        # Chrome判定
        if app_version.include? 'Chrome'
          'Google Chrome'
        else
          # Safari判定
          'Safari'
        end
        # FireFox判定
      elsif user_agent.include? 'FireFox'
        'FireFox'
        # その他
      else
        'unknown'
      end
    end

    # browser_versionを判定する
    def browser_version_check
      case browser
      when 'Internet Explorer' then
        st = user_agent.index('MSIE')
        en = user_agent.index(';')
        plus = 4
      when 'Opera' then
        st = user_agent.index('Version')
        en = user_agent.length
        plus = 8
      when 'Safari' then
        st = user_agent.index('Version')
        en = user_agent.index(' ', st)
        plus = 8
      when 'Google Chrome' then
        st = user_agent.index('Chrome')
        en = user_agent.index(' ', st)
        plus = 7
      when 'FireFox' then
        st = user_agent.index('FireFox')
        en = user_agent.length
        plus = 8
      else
        return ''
      end
      user_agent.slice(st + plus..en)
    end
end

app/controllers/analytics_controller.rb
class AnalyticsController < ApplicationController
  def index
    day = Impression.day_select
    week = Impression.week_select
    month = Impression.month_select

    # All
    # PV数
    @allcount = Impression.count
    # URL別
    @each_url_data = Impression.url_count
    # browser別
    @each_browser_data = Impression.browser_count
    # 端末別
    @each_platform_data = Impression.platform_count

    # Day
    # PV数
    @daycount = day.count
    # URL別
    @day_each_url_data = day.group(:url).group_by_hour_of_day(:created_at, format: '%l %P').count
    # browser別
    @day_each_browser_data = day.browser_count
    # 端末別
    @day_platform_data = day.platform_count

    # Week
    # PV数
    @weekcount = week.count
    # URL別
    @week_each_url_data = week.group(:url).group_by_day(:created_at, format: '%m/%d').count
    # browser別
    @week_each_browser_data = week.browser_count
    # 端末別
    @week_platform_data = week.platform_count

    # Month
    # PV数
    @monthcount = month.count
    # URL別
    @month_each_url_data = month.group(:url).group_by_day(:created_at, format: '%m/%d').count
    # browser別
    @month_each_browser_data = month.browser_count
    # 端末別
    @month_platform_data = month.platform_count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/impression_controller.rb
class ImpressionController < ApplicationController
  protect_from_forgery with: :null_session

  def create
    # UserAgentを参照し、ブラウザ等判定をする
    impression = Impression.new(agent_params)
    impression.save
    render :nothing => true
  end

  private
    def agent_params
      params.require(:agent).permit(:app_name, :app_version, :device, :user_agent, :now_url)
    end
end

app/helpers/analytics_helper.rb
module AnalyticsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/impression_helper.rb
module ImpressionHelper
end

app/views/analytics/index.html.erb
<div class="container-fluid">
  <h2>All Pageviews
    <%= @allcount %></h2>
  <div class="row">
    <div class="col-sm-8">
      <div class="chart-wrapper">
        <div class="chart-title">
          Pageviews by URL ( All )
        </div>
        <div class="chart-stage">
          <%= bar_chart @each_url_data %>
        </div>
        <div class="chart-notes">
          This is a sample text region to describe this chart.
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="chart-wrapper">
        <div class="chart-title">
          Pageviews by browser ( All )
        </div>
        <div class="chart-stage">
          <%= pie_chart @each_browser_data %>
        </div>
        <div class="chart-notes">
          Notes go down here
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-8">
      <div class="chart-wrapper">
        <div class="chart-title">
          Pageviews by URL ( Day )
          <b><%= @daycount %></b>
        </div>
        <div class="chart-stage">
          <%= line_chart @day_each_url_data %>
        </div>
        <div class="chart-notes">
          Notes go down here
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="chart-wrapper">
        <div class="chart-title">
          Pageviews by browser ( Day )
        </div>
        <div class="chart-stage">
          <%= pie_chart @day_each_browser_data %>
        </div>
        <div class="chart-notes">
          Notes go down here
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-8">
      <div class="chart-wrapper">
        <div class="chart-title">
          Pageviews by URL ( Week )
          <b><%= @weekcount %></b>
        </div>
        <div class="chart-stage">
          <%= line_chart @week_each_url_data %>
        </div>
        <div class="chart-notes">
          Notes go down here
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="chart-wrapper">
        <div class="chart-title">
          Pageviews by browser ( Week )
        </div>
        <div class="chart-stage">
          <%= pie_chart @week_each_browser_data %>
        </div>
        <div class="chart-notes">
          Notes go down here
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-8">
      <div class="chart-wrapper">
        <div class="chart-title">
          Pageviews by URL ( Month )
          <b><%= @monthcount %></b>
        </div>
        <div class="chart-stage">
          <%= line_chart @month_each_url_data %>
        </div>
        <div class="chart-notes">
          Notes go down here
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="chart-wrapper">
        <div class="chart-title">
          Pageviews by browser ( Month )
        </div>
        <div class="chart-stage">
          <%= pie_chart @month_each_browser_data %>
        </div>
        <div class="chart-notes">
          Notes go down here
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-4">
      <div class="chart-wrapper">
        <div class="chart-title">
          Pageviews by device ( All )
        </div>
        <div class="chart-stage">
          <%= pie_chart @each_platform_data %>
        </div>
        <div class="chart-notes">
          Notes go down here
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="chart-wrapper">
        <div class="chart-title">
          Pageviews by device ( Day )
        </div>
        <div class="chart-stage">
          <%= pie_chart @day_platform_data %>
        </div>
        <div class="chart-notes">
          Notes go down here
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="chart-wrapper">
        <div class="chart-title">
          Pageviews by device ( Week )
        </div>
        <div class="chart-stage">
          <%= pie_chart @week_platform_data %>
        </div>
        <div class="chart-notes">
          Notes go down here
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-8">
      <div class="chart-wrapper">
        <div class="chart-title">
          Notes go down here
        </div>
        <div class="chart-stage">
          <div class="dummy"></div>
        </div>
        <div class="chart-notes">
          Notes go down here
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="chart-wrapper">
        <div class="chart-title">
          Pageviews by device ( Month )
        </div>
        <div class="chart-stage">
          <%= pie_chart @month_platform_data %>
          <div class="chart-notes">
            Notes go down here
          </div>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PvApp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
    <%= javascript_include_tag "//code.highcharts.com/highcharts.js", "chartkick" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <div class="application">
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
              </button>
              <a class="navbar-brand" href="../">
                <span class="glyphicon glyphicon-chevron-left"></span>
              </a>
              <%= link_to 'Dashboard PV_app', analytics_path ,class: "navbar-brand" %>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav navbar-left">
                <li><%= link_to 'Home', analytics_path %></li>
                <li><a href="#">Team</a></li>
                <li><%= link_to 'Source', 'https://github.com/gondodo/pv_app' %></li>
                <li><a href="#">Community</a></li>
                <li><a href="#">Technical Support</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
  </header>

    <%= yield %>

    <footer class="container-fluid">
      <hr>
      <p class="small text-muted">
        Built with &#9829; by <%= link_to 'gondodo', 'https://github.com/gondodo/pv_app' %> 2016
      </p>
    </footer>
  </body>
</html>